---
title: Robert of Blog
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Robert's Junk
baseurl: 
url: 
twitter_username: robertholak
github_username: rholak
github:
  repoistory_name: beefnuggets
  repository_url: http://github.com/
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-assets
- jekyll-gist
excerpt_separator: "<!--more-->"
show_excerpts: true
permalink: "/:year/:month/:day/:title/"
theme: minima
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- script/
- README.md
- .travis.yml
